"""Fix relationships

Revision ID: 3e3b2198eae8
Revises: a57c8f431868
Create Date: 2025-07-17 15:34:01.055473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3b2198eae8'
down_revision = 'a57c8f431868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_payments_client_id', 'users', ['client_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_invoices_client_id', 'users', ['client_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_payments_client_id', type_='foreignkey')
        batch_op.drop_column('client_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_invoices_client_id', type_='foreignkey')
        batch_op.drop_column('client_id')


    # ### end Alembic commands ###
