name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  # ✅ Linting Stage
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install flake8 black isort bandit
          pip install -r requirements.txt

      - name: Run Flake8
        run: flake8 .

      - name: Run Black (check only)
        run: black --check .

      - name: Run isort (check only)
        run: isort . --check-only

      - name: Run Bandit (security checks)
        run: bandit -r .

  # ✅ Testing Stage
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          pytest  # or your test runner command
